# Use the official Python image
FROM python:3.10-slim-buster

# Set working directory
WORKDIR /app

# Copy all files
COPY ./ /app

RUN apt-get update \
    && apt-get install -y netcat curl git make gcc postgresql python3-dev libpq-dev \
    && apt-get clean

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "-m", "scripts.generators.driver.driver_coordinates_generator"]